const path =require('path');

module.exports={
    devServer:{
        proxy:{
            "/v1":{
                target:"https://fe-wcgi.jianke.com",
                changeOrigin:true
            },
            "/m":{
                target:"https://jktt-api.jianke.com",
                changeOrigin:true
            },
            "/v2":{
                target:"https://fe-wcgi.jianke.com",
                changeOrigin:true
            },
            "/Search":{
                target:"http://m.360kad.com",
                changeOrigin:true
            },
            "/category":{
                target:"https://wcgi.jianke.com",
                changeOrigin:true
            },
            "/api":{
                target:"http://39.97.33.178",
                changeOrigin:true
            },
            "/users":{
                target:"http://localhost:9000",
                changeOrigin:true
            },
            "/goods":{
                target:"http://localhost:9000",
                changeOrigin:true
            },
        }
       


    },
    //别名配置
    configureWebpack:{
        resolve:{
            alias:{
                "@":path.join(__dirname,"./src"),
                "@api":path.join(__dirname,"./src/api"),
                "@assets":path.join(__dirname,"./src/assets"),
                "@common":path.join(__dirname,"./src/common"),
                "@components":path.join(__dirname,"./src/components"),
                "@lib":path.join(__dirname,"./src/lib"),
                "@pages":path.join(__dirname,"./src/pages"),
                "@router":path.join(__dirname,"./src/router"),
                "@store":path.join(__dirname,"./src/store"),
                "@utils":path.join(__dirname,"./src/utils")
            }
        }
    }
}